#!/bin/ksh
# $OpenBSD$

# Installation:
# 1. build and move ogo to /usr/local/sbin/: install -m 755 ogo /usr/local/sbin/ogo
# 2. create system user: useradd -s /sbin/nologin -d /var/empty -c "file service" _ogo
# 3. prepare working directory: mkdir /var/ogo && chown _ogo:wheel /var/ogo
# 4. cp rcd /etc/rc.d/ogo && chmod 555 /etc/rc.d/ogo
# 5. rcctl enable ogo
#
# Service commands:
# rcctl start ogo
# rcctl check ogo
# rcctl stop ogo
#
# Logs will be in /var/log/daemon

rc_pid_file="/var/run/ogo.pid"
daemon="/usr/local/sbin/ogo"
daemon_user="_ogo"
daemon_flags="-d /var/ogo -p $rc_pid_file"
daemon_logger="daemon.info"

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_pre() {
    # create pid file with correct permissions
    install -o "$daemon_user" -g "$daemon_user" -m 644 /dev/null "$rc_pid_file"
}

rc_cmd $1
